
import React from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Download, FileText, Share2 } from 'lucide-react';

interface ClaimNarrative {
  structuredText: string;
  emotions: string[];
  tags: string[];
  timestamp: string;
  location: string;
  severity: 'low' | 'medium' | 'high';
}

interface ReportDownloadProps {
  narrative: ClaimNarrative | null;
}

const ReportDownload: React.FC<ReportDownloadProps> = ({ narrative }) => {
  if (!narrative) return null;

  const downloadReport = () => {
    const reportContent = `
INSURANCE CLAIM REPORT
Generated by ClaimNarrator AI

INCIDENT NARRATIVE:
${narrative.structuredText}

INCIDENT DETAILS:
Time: ${narrative.timestamp}
Location: ${narrative.location}
Severity: ${narrative.severity.toUpperCase()}

EMOTIONAL CONTEXT:
${narrative.emotions.join(', ')}

CLAIM CATEGORIES:
${narrative.tags.join(', ')}

Generated on: ${new Date().toLocaleDateString()}
    `;

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `claim-report-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const shareReport = () => {
    if (navigator.share) {
      navigator.share({
        title: 'Insurance Claim Report',
        text: narrative.structuredText,
      });
    } else {
      // Fallback: copy to clipboard
      navigator.clipboard.writeText(narrative.structuredText);
      alert('Report copied to clipboard!');
    }
  };

  return (
    <Card className="w-full max-w-2xl mx-auto">
      <CardHeader>
        <CardTitle className="flex items-center gap-2 text-blue-700">
          <FileText className="w-5 h-5" />
          Export Report
        </CardTitle>
      </CardHeader>
      <CardContent>
        <div className="flex gap-3">
          <Button 
            onClick={downloadReport}
            className="flex-1 bg-green-600 hover:bg-green-700"
          >
            <Download className="w-4 h-4 mr-2" />
            Download Report
          </Button>
          <Button 
            onClick={shareReport}
            variant="outline"
            className="flex-1"
          >
            <Share2 className="w-4 h-4 mr-2" />
            Share
          </Button>
        </div>
      </CardContent>
    </Card>
  );
};

export default ReportDownload;
